### ISSUE TITLE
Remove __pycache__ directory

### ISSUE THREAD

**Issue by ykl7** [MUSoC/PoS-Tagging#5]
@vdasu Please add ```__pycache__/``` to the ```.gitignore``` and remember to remove it from tracking using ```git rm --cached __pycached__```. Before continuing work, ppen a new PR for the same and reference the issue

**Comment by vdasu** [comment]
@ykl7 I've already [added](https://github.com/MUSoC/PoS-Tagging/blob/013ab06c2d91e8c8e129d71d313dbb7ebd414acb/.gitignore#L2) `__pycache__/` to `.gitignore`.

**Comment by ykl7** [comment]
Oh yeah sorry about that.
